### ISSUE TITLE
Mate crashes when the api server is unavailable at runtime

### ISSUE THREAD

**Issue by linki** [linki/mate#2]
```
time="2016-11-09T17:37:23Z" level=fatal msg="Unable to watch list of services: an error on the server has prevented the request from succeeding (get services)"
```

mate comes back fine but after a while has a high number of restarts (which just increase over time) which will lead to an alert in zmon. killing the pod will clear the alert but that is a bad solution.

**Comment by ideahitme** [comment]
I believe it was addressed here https://github.com/zalando-incubator/mate/pull/20
