### ISSUE TITLE
Support multiple hosted-zones

### ISSUE THREAD

**Issue by ideahitme** [linki/mate#22]
The case when the AWS account has multiple hosted zones and services/ingress may specify various domain where the DNS record needs to be created ( annotation in `service` case). Maybe it makes sense to deduce where the ELB needs to be created. 

Another point is that we don't really need to pass --aws-hosted-zone flag, as this information can be retrieved in runtime, and correct hosted zone (with its id) can be automatically selected based on the `kubernetes-domain` (might need to be renamed to `kubernetes-default-domain`)

**Comment by hjacobs** [comment]
We would still need some hosted zone flag to figure out the default hosted zone to use when the annotation is missing.

**Comment by ideahitme** [comment]
when annotation is missing then we use the template + kubernetes-default-domain

**Comment by ideahitme** [comment]
or we can pass the default kubernetes domain directly into the template: 
```
{{.Name}}-{{.Namespace}}.example.com
```

**Comment by hjacobs** [comment]
@ideahitme the templating approach sounds even better!

**Comment by ideahitme** [comment]
one potential case requires special attention is having two hosted zones of format: 

`example.com`,
`sub.example.com`

**Comment by hjacobs** [comment]
@ideahitme yes, in that case the longer (more specific) one should be selected by Mate I guess.

**Comment by ideahitme** [comment]
fixed as per https://github.com/zalando-incubator/mate/pull/26
