### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by hjacobs** [linki/mate#25]
I propose renaming this project to something more meaningful. The project name should immediately tell people what this is about (managing Route 53 or GCP DNS entries), so I propose something like:

* kube-cloud-dns-controller
* kube-cloud-dns-manager
* kube-external-dns-controller
* kube-external-dns-manager

I'm open for any other name as long as it accurately represents the project's purpose.

**Comment by hjacobs** [comment]
@ideahitme already performed a small internal poll to gather name suggestions.

**Comment by ideahitme** [comment]
@hjacobs 
<img width="742" alt="screen shot 2016-12-12 at 15 32 39" src="https://cloud.githubusercontent.com/assets/23239537/21102921/8314a44a-c080-11e6-99bc-1a64c094d929.png">

**Comment by ideahitme** [comment]
Voting stage 1 
<img width="475" alt="screen shot 2016-12-12 at 18 55 51" src="https://cloud.githubusercontent.com/assets/23239537/21110231/a7df4976-c09c-11e6-840a-efd0fda7c61c.png">

**Comment by ideahitme** [comment]
<img width="710" alt="screen shot 2017-01-10 at 22 45 55" src="https://cloud.githubusercontent.com/assets/23239537/21826126/a078eea2-d786-11e6-8704-616c1cb91a3e.png">
**Final voting results**

We will stick with `Mate` :)
