### ISSUE TITLE
Mate should not crash on invalid annotation key

### ISSUE THREAD

**Issue by linki** [linki/mate#3]
A wrong name without DNS zone for example will crash:

    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        zalando.org/dnsname: foobar

**Comment by ideahitme** [comment]
this was addressed in this PR too https://github.com/zalando-incubator/mate/pull/20 . Mate does not crash on invalid annotation key. In AWS consumer case, the record will be skipped, hence no error generated.
