### ISSUE TITLE
Dockerfile build process is undocumented

### ISSUE THREAD

**Issue by paultiplady** [linki/mate#35]
Looks like the Dockerfile is dependent on being built in a specific environment; is it possible to unpick that so that independent builds are possible? Perhaps there are just some instructions missing.

```
# docker build -t mate:0.3.0 .
Sending build context to Docker daemon 29.66 MB
Step 1 : FROM registry.opensource.zalan.do/stups/alpine:UPSTREAM
Pulling repository registry.opensource.zalan.do/stups/alpine
Tag UPSTREAM not found in repository registry.opensource.zalan.do/stups/alpine
```

**Comment by paultiplady** [comment]
From `make build.docker` output:

```
# make build.docker
...
[go build output]
...
docker build --rm -t "registry-write.opensource.zalan.do/teapot/mate:v0.3.0" -f Dockerfile.upstream .
Sending build context to Docker daemon 59.15 MB
Step 1 : FROM registry.opensource.zalan.do/stups/alpine:
Error parsing reference: "registry.opensource.zalan.do/stups/alpine:" is not a valid repository/tag
make: *** [build.docker] Error 1
```

Think this is actually just a docs issue; need to know how to populate the upstream dockerfile. For now I've just manually updated the generated Dockerfile.upstream to use a valid alpine tag.

**Comment by Raffo** [comment]
Yes the Dockerfile is pretty much used with the Makefile, which is also used to push to our Docker registry. While you can pull from it freely without any auth, you can't push to it if you're not authenticated/authorized. Would it be fine to just change the `README` to make this clear and suggest what to modify?

**Comment by paultiplady** [comment]
Given that you're overriding UPSTREAM in your makefile by the looks of it, could you just do `FROM alpine...:latest` and then `s/latest/your_stuff/` ? Think that would be functionally equivalent, but would leave the Dockerfile as strictly valid.

**Comment by Raffo** [comment]
As discussed in #37, this is not possible as the used registry is not supporting the tag `latest`. Thx @sarnowski for remembering me.

**Comment by ideahitme** [comment]
Additionally, there is a compliance requirement of having `scm-source` injected into the docker image. To avoid making additional step of creating scm-source I would just advise to document explicitly that `make` command has to be used.

**Comment by ideahitme** [comment]
unfortunately there is a `pierone` dependency in the `Makefile` which makes it currently impossible to build the docker locally without having `pierone` cli installed.

**Comment by Raffo** [comment]
We could implement a make target to replace completely the FROM with ubuntu:latest or another image.

**Comment by ideahitme** [comment]
Dockerfile was modified for external users, so now it will be using alpine:latest from the Docker file. And `make build.docker` command can be run without any additional tools required. For Zalando internal compliance images, another dockerfile `Dockerfile.zalando` is created and official releases will be created via this new Dockerfile.

**Comment by paultiplady** [comment]
Thanks for accommodating those of us outside your org 👍  appreciate the changes here.
