### ISSUE TITLE
Investigate and document alternative implementations

### ISSUE THREAD

**Issue by linki** [linki/mate#4]
single-cluster kubernetes uses an in-cluster skydns for internal dns records. logically, a federated-cluster setup needs an equivalent. the approach seems to be to use google cloud dns and aws route 53 to solve this. i assume the dns entries are designed for internal use only (as with skydns) but they could also make this tool obsolete.

**Comment by linki** [comment]
also see
* https://github.com/kubernetes/kubernetes/issues/28525 (DNS names for load balancer services)
* https://github.com/kubernetes/kubernetes/tree/master/federation/pkg/dnsprovider (federation dns provider)
* https://github.com/kubernetes/kops/tree/master/dns-controller (similar thing from Kops)
* https://github.com/wearemolecule/route53-kubernetes
* https://github.com/antonosmond/k8s-route53

**Comment by hjacobs** [comment]
@linki I guess we can close this issue in the light of our new ["External DNS" Kubernetes Incubator project](https://github.com/kubernetes-incubator/external-dns)?

**Comment by ideahitme** [comment]
@hjacobs yes I think so
